@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class DaysPerRunFlagHandler {
  + DaysPerRunFlagHandler(): 
  + handleRequest(TerminalFlagRequest): void
}
class FlagHandler {
  + FlagHandler(): 
  # m_successor: FlagHandler
  + setSuccessor(FlagHandler): void
  + handleRequest(TerminalFlagRequest): void
}
class GridSizeFlagHandler {
  + GridSizeFlagHandler(): 
  + handleRequest(TerminalFlagRequest): void
}
class InitialOrganismCountFlagHandler {
  + InitialOrganismCountFlagHandler(): 
  + handleRequest(TerminalFlagRequest): void
}
class TerminalFlagRequest {
  + TerminalFlagRequest(String, Map): 
  - map: Map
  - terminalCommand: String
  - numOfDays: int
  + getMap(): Map
  + getNumOfDays(): int
  + setNumOfDays(int): void
  + setMap(Map): void
  + getTerminalCommand(): String
}

DaysPerRunFlagHandler            -[#000082,plain]-^  FlagHandler                     
GridSizeFlagHandler              -[#000082,plain]-^  FlagHandler                     
InitialOrganismCountFlagHandler  -[#000082,plain]-^  FlagHandler                     
@enduml
